---
language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - sphinx-build -b html source build/html

notifications:
  irc:
    channels:
      - "irc.freenode.org#betacloud"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
