---
language: python
python:
  - "3.6"

addons:
  apt:
    packages:
    - lftp

install:
  - pip install -r requirements.txt

script:
  - scripts/build.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#betacloud"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
